### ISSUE TITLE
Permission to submit to Greenlight

### ISSUE THREAD

**Issue by toobulkeh** [gliptic/liero#15]
Hey @gliptic,
I would love to submit Liero to Steam's Greenlight.

I use to put in a ton of hours into Liero and would love to see it easily distributed as a free game through Steam's platform.

I'm willing to foot the Greenlight fee and put in the development hours to fit the Steam requirements.

In order to submit it to Greenlight I need to have explicit authorization to meet their [legal requirements](http://steamcommunity.com/workshop/editgame/?appid=765).

Thanks for your consideration!

**Comment by TimmermanV** [comment]
Great idea! It would be even better if we can make Liero mods easily accessible.

**Comment by CanadianJeff** [comment]
fantastic idea please lets see this happen

**Comment by CanadianJeff** [comment]
seeing as Greenlight is basically gone could just pay the fees and get this game up on steam

**Comment by grawlinson** [comment]
It can't be distributed due to copyright issues.

**Comment by CanadianJeff** [comment]
who owns the copyrights? www.liero.com is no longer up

**Comment by barnaba** [comment]
I think George meant sounds and other assets (and most good maps), not the
actual code.

I remember there was an attempt to fix this in lierolibre so it could be
distributed in Debian, so unless there's some other issues it should be
doable
