### ISSUE TITLE
Icon resources

### ISSUE THREAD

**Issue by mefistotelis** [gliptic/liero#20]
Surprised to see this still has no icon.

Prepared a set for my install - feel free to adopt.
The icons are based on the screenshot from Wikipedia.
![liero-pic-16](https://user-images.githubusercontent.com/11463396/146039140-70467c40-b17b-4f96-9506-8576774f4486.png)
![liero-pic-32](https://user-images.githubusercontent.com/11463396/146039144-ecad23e9-ef30-42ed-8cd7-2f0fceece1d4.png)
![liero-pic-48](https://user-images.githubusercontent.com/11463396/146039146-9f7ceea0-b016-4598-b06f-49688d573ca1.png)
![liero-pic-64](https://user-images.githubusercontent.com/11463396/146039148-07692a71-ca9e-4f86-8809-02e9281c14bb.png)
![liero-pic-70](https://user-images.githubusercontent.com/11463396/146039149-43bab7cf-cd47-46f1-9db1-f0dc9f0c799d.png)

For Windows - icons are typically compiled with Resource Compiler and built into EXE.
For Linux - they are just supplied as PNGs.

**Comment by ahockersten** [comment]
Stuff in #26 resolves this, although I have no particular attachment to that icon so if we want another one (like this fine one :)) I wouldn't be opposed.

**Comment by mefistotelis** [comment]
The already merged icon looks cleaner. Not sure though how it looks within managers, like Windows explorer / Gnome desktop menu.

The one I made shows lots of features, but showing features is not really icons purpose. So, I can't say which one is better either.

**Comment by ahockersten** [comment]
![image](https://github.com/user-attachments/assets/ada68bf1-e334-449c-a273-fb1c1f9d58c2)
This is what it looks like on Windows. Gnome should be similar, I haven't tested it in a while, but I'm pretty sure it works as intended.

**Comment by mefistotelis** [comment]
Looks good. No need to keep this issue open then.
